FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN corepack enable
RUN corepack prepare pnpm@10.16.1 --activate

RUN pnpm install

RUN pnpm --filter @cloudcart/web build

FROM nginx:alpine

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]