apiVersion: v1
kind: ConfigMap

metadata:
  name: payment-config
  namespace: cloudcart

data:
  NODE_ENV: "production"

  PORT: "4005"

  MONGODB_URI: "mongodb://mongodb:27017/cloudcart"

  ORDER_SERVICE_URL: "http://order:4004"

  CORS_ORIGIN: "*"

  PAYMENT_SUCCESS_RATE: "90"
